version: "3"

networks:
  api-network:

services:
  plapp-api-db:
    image: postgres:latest
    container_name: plapp-api-db
    ports:
      - "5433:5432"
    env_file:
      - postgres.env
    volumes:
      - database-data:/var/lib/postgresql/data
    networks:
      - api-network


  plapp-api-service:
    image: maven:latest
    working_dir: $PWD
    container_name: plapp-api-service
    volumes:
      - $PWD:$PWD
      - /var/run/docker.sock:/var/run/docker.sock
      - ~/.m2:/root/.m2
    expose:
      - "8080"
    command: mvn spring-boot:run
    networks:
      - api-network
    depends_on:
      - plapp-api-db

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - plapp-api-service
    ports:
      - "4000:4000"
    networks:
      - api-network

volumes:
  database-data:

